#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CleverWeather.Droid.Resource", IsApplication=true)]

namespace CleverWeather.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::CleverWeather.Droid.Resource.String.library_name;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::CleverWeather.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::CleverWeather.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int xamarinblue = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int cbc_white_00 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int cbc_white_01 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int cbc_white_02 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int cbc_white_03 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int cbc_white_04 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int cbc_white_05 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int cbc_white_06 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int cbc_white_07 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int cbc_white_08 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int cbc_white_09 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int cbc_white_10 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int cbc_white_11 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int cbc_white_12 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int cbc_white_13 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int cbc_white_14 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int cbc_white_15 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int cbc_white_16 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int cbc_white_17 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int cbc_white_18 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int cbc_white_19 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int cbc_white_20 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int cbc_white_21 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int cbc_white_22 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int cbc_white_23 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int cbc_white_24 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int cbc_white_25 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int cbc_white_26 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int cbc_white_27 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int cbc_white_28 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int cbc_white_29 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int cbc_white_30 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int cbc_white_31 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int cbc_white_32 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int cbc_white_33 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int cbc_white_34 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int cbc_white_35 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int cbc_white_36 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int cbc_white_37 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int cbc_white_38 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int cbc_white_39 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int clever_weather = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic_location_place = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_menu_refresh = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int monoandroidsplash = 2130837547;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			// aapt resource value: 0x7f030004
			public const int app_name = 2130903044;
			
			// aapt resource value: 0x7f030003
			public const int hello = 2130903043;
			
			// aapt resource value: 0x7f030002
			public const int library_name = 2130903042;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MyTheme = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int MyTheme_ActionBar_TitleTextStyle = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int MyTheme_ActionBarStyle = 2131034114;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
